### ISSUE TITLE
Adhere to stated style guide

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz#75]
... or clearly document exceptions.

The project Wiki claims the code loosely follows the Google Java Style Guide. The project should more strictly adhere to the standards in that document or should document the exceptions to the style guide. Of note, the following rules are violated (ordered by appearance in style guide itself):

- 2.3.1 Whitespace characters
- 3.3.3 Ordering and spacing
- 3.4.2 Class member ordering
- 4.1.1. Braces are used where optional
- 4.2 Block indentation: +2 spaces
- 4.4 Column limit: 80 or 100
  - Note: While columns never exceed 100, it appears 80 was the intended target and that is exceeded in multiple locations.
- 4.5.2 Indent continuation lines at least +4 spaces
- 5.2 Rules common to all identifiers
  - Use of unicode (non-ascii) member names
- 5.2.2 Class names
  - Some class names are not nouns, eg. “ClusterToCurves”
- 5.3 Camel case: defined
  - Some references like: “anXMLVar” should be “anXmlVar”
- 6.3 Static members: qualified using class
- 7.2 The summary fragment

**Comment by pmpowers-usgs** [comment]
Source edits:
* 2.3.1Updated all source to use spaces (2)
* 3.3.3 Cleaned and reordered imports
* 3.4.2 Class member ordering: structure of most classes is pretty good (e.g. inner classes located near methods that use them); this will be revisited as the codebase is cleaned further. No strict guidance is supplied in style guide.
* 4.1.1 Missing braces added
* 4.2 Block indentation fixed with tab-to-space and reformat
* 4.4 Code-line-length=100; javadoc-line-length=80
* 4.5.2 most wrapped lines should now be +4 spaces with auto-formatting
* 5.2 non-ascii member names: we prefer the use of unicode representations of mathematical symbols
* 5.2.2 Class name not a noun. The example provided is an inner class in a private factory class. If any ambiguity exists, the example should be referenced as Transforms.ClusterToCurves
* 5.3 Most classes, methods, and fields that are not part of as yet unrefactored opensha classes of classes slated for deprecation have properly styled camel-case names
* 6.3 This rule states that "_when_ a reference to a static class member needs to be qualified", not that all static members or methods actually be qualified. That said, additional clarifying guidance has been added to the wiki.
* 7.2 This will be improved with a more thorough javadoc review. The intent is for most classes in nshmp-haz to be private and that once verification is complete a limited number of factory and high-level classes will remain public; these will be reviewed for comment completeness.
